### ISSUE TITLE
Question, is Thor pointing to the correct repos?

### ISSUE THREAD

**Issue by Terrofmen** [VFPX/Thor#10]
Hello ,

While installing repos I noticed it gives the date of the files that it installs. I looked in the folder to read through the code and have noticed the files are older than the files being hosted on GitHub. My question is, is Thor still pointing to codeplex website and not the Github website?

For example:
Thor version of Foxcharts is 1.20 roughly 2009
GitHub version of Foxcharts is 1.37/1.46/1.47 roughly 2018-2019

Thor version of FoxBarcode is 1.12 roughly 2013
Github version of FoxBarcode is 1.17 roughly 2017

It appears to me that Thor is looking at the wrong location for the repo of these files. Is there any way to update this or do I need to update my version of Thor?

**Comment by rschummer** [comment]
Each of the projects is managed by a different project manager. The control the update process. Unfortunately, only some of the project managers have moved their updates to GitHub and some of the more mature and some of the deprecated projects are still downloading from the vfpxrepository.com Web site, where many of the updates were hosted previously (or still). 

It takes time to move the updates to GitHub. Since this is open source, anyone can jump in if they have the time and energy.

**Comment by Terrofmen** [comment]
Hey,

Thanks for the reply. I have some free time this week and next. If I could
be shown what is going on then I could probably help more projects over to
the github location.

Let me know,
Taylor

**Comment by rschummer** [comment]
Taylor, 

While I appreciate the offer, I believe after a little rethinking, the issue should be handled by the project managers for the most part because they have to post future updates to the correct spot or nothing will work moving forward. Having someone else do the work could lead to more confusion.

**Comment by Terrofmen** [comment]
That makes sense. No worries. Hopefully everything can get moved over soon. 

Taylor

**Comment by BobWilkes** [comment]
"You" also need to update Thor links. For example,  Thor Tools, Thor, What's new still points to CodePlex, so don't forget those.
