### ISSUE TITLE
Run Thor tools without running thor.app

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/Thor#103]
My thor.app giving problem so is possible to Run Thor tools without running thor.app ?
I want to use below tools:
Beautifyx
Create Locals
mDots
Gofish && i can use this by Do Gofish.app

Warm regards,
mk.

**Comment by Jimrnelson** [comment]
@mksharmamk 

Can you describe how far the installation process gets before it halts?

Do you get the Check For Updates screen where you can select projects to install?  Were you able to install any projects?

Thor creates log files named 'Thor_CFU_Log_*.txt' in sys(2023).  Can you attach the most recent?  That might help

**Comment by Jimrnelson** [comment]
None of your files are being downloaded.  That's why you're seeing this, repeatedly:

22:03:35 Requesting file Updates.zip?=_6MI1BA52D&_6MI1BA539 from server.
thor_proc_downloadfilefromurl.prg, line 81
22:04:17 URL cannot be opened
thor_proc_downloadfilefromurl.prg, line 92

Notice that there's about a 40 second delay there waiting for the response.

As I've indicated before, I can't help you with this problem.  It must be something in your configuration (firewall, maybe) that is prohibiting the download.

Sorry I can't do more to help.

**Comment by Jimrnelson** [comment]
No, until you have been able to get Thor.App to run, none of the tools have been downloaded, so there is nothing for you to run.
