### ISSUE TITLE
Uninstall from CFU

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#112]
## 📝 Provide a description of the new feature

How to uninstall a project from Thor as a whole? At least the code, data might be an extra problem.

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
This topic has been mentioned before, by Tamar, I believe.

Most Thor projects live in their own folder, either in Tools\Apps or Tools\Components.  

The folders are accessible here and could be removed manually

![image](https://github.com/VFPX/Thor/assets/81179335/d63746d1-2af8-4582-8742-bed398e48c1f)

It would quite straightforward to modify some existing Thor screen to do this.

There would still be some leftover issues:

- Some Thor projects create tools (GF, for instance, creates quite a few).  There is no programmatic way that I can see such that these tools could be automatically removed.
- I have to assume that some projects create data in other their own Thor sub-folder.  Again, there's no way that Thor can no about what that would be so that it could be removed.

**Comment by lscheffler** [comment]
The folders / files in Apps; Proc and  Components. For the part that is installed by Thor it would be possible to trace the changes (and even provide a template for the stuff installed) while installing. This is just boring work, nothing tricky. One could even provide a table of *know* information for old installations.   
The main problem are the tools like GF creates them (It's now not as much as it was before), and that they will kind of work, even if the main stuff is removed.   
Data scattered around is just data. A doc file will be kept is Word is removed, I see no problem there, most programs will do this.

**Comment by Jimrnelson** [comment]
@lscheffler 

Apart from the concept of removing folders and files from folders Tools\Apps and Tools\Components, this is not a topic I wish to delve more deeply into unless there are really simple solutions.

First of all, there has been no clamoring for this feature.  Before the end of last year, when Tamar mentioned it, I had never been asked about how to remove projects from Thor.  Without some significant interest, I can't see investing any time in this.

Second, one of the conscious goals for Thor, and in particular CFU, is to keep it as barebones as possible.  Adding complication adds likelihood of failure; I do not want to tinker with the CFU process unless absolutely necessary.

Third, there is a reasonable process that a user can do _manually_ to achieve the same effect:

1. Remove the folder from Tools\Apps or Tools\Components
2. Use GF (or CR) to find all tools that reference the deleted folder.  For instance, searching for `Tools\Apps\GoFish` finds all the tools that reference the the GoFish folder.

If anything, I suggest that easily accessible documentation on these steps would be sufficient.

**Comment by lscheffler** [comment]
> Apart from the concept of removing folders and files from folders Tools\Apps and Tools\Components, this is not a topic I wish to delve more deeply into unless there are really simple solutions.

Because of that I called it a discussion rather then an issue or a request. Nothing you should do at all. This is a hypothetical discussion, nothing more.
 
> First of all, there has been no clamoring for this feature. Before the end of last year, when Tamar mentioned it, I had never been asked about how to remove projects from Thor. Without some significant interest, I can't see investing any time in this.

Full ACK. It has some value while developing - it's a pain to remove all the files every time.

**Comment by Jimrnelson** [comment]
@lscheffler 

> Full ACK. It has some value while developing - it's a pain to remove all the files every time.

Can you explain this a little?  I don't understand what files you are referring to or how Thor/CFU could have any knowledge of them.

Since GoFish5.APP is self-contained, there is no need for CFU to deliver anything other than that file.  All the source code that is delivered with it dates back to the days before GitHub where there was no other way to deliver source code.

It almost seems like you are running CFU many times.  If so, I believe that is not necessary and we should find a way so that you can avoid it.  I for one run CFU only when I am ready to release a project to the world.

**Comment by lscheffler** [comment]
> @lscheffler
> 
> > Full ACK. It has some value while developing - it's a pain to remove all the files every time.
> 
> Can you explain this a little? I don't understand what files you are referring to or how Thor/CFU could have any knowledge of them.
> 
> Since GoFish5.APP is self-contained, there is no need for CFU to deliver anything other than that file. All the source code that is delivered with it dates back to the days before GitHub where there was no other way to deliver source code.
> 
> It almost seems like you are running CFU many times. If so, I believe that is not necessary and we should find a way so that you can avoid it. I for one run CFU only when I am ready to release a project to the world.

Possibly different styles of debuggging. If I test for release I try to update as well as to run from scratch - but this is hard if files remain (again, we ignore data). In special for GoFish, there is a lot of old version menue (we had this other issue about this) to remove.

And since I changed something for GF, sometimes I test with the old (v5) version of GF. Guess what the self-registering logic of GF is doing to my Thor Tools folder. I need to clean this again and again and again.

The same is for VFPDeployment, it put files in  tools; tools/apps; tools/proc, so I must remove this from time to time.

And picking files in tools folder is a pain.

**But again, this is nothing you need to care. There is no elegant fix, and we can not change most of the tools anyway.**
