### ISSUE TITLE
Thor Tool Manager Errors Out After New Install of Thor

### ISSUE THREAD

**Issue by pivoten-psherwood** [VFPX/Thor#173]
I removed Thor from my system because of problems with GoFish and reinstalled the latest using the installation instructions.

After installing and running through the update I tried to bring up the Tool Manager from the Thor menu. It gets this error.![image](https://github.com/VFPX/Thor/assets/116839069/77914a68-d679-4a83-95d4-3fd0260a1cdc)

If you suspend it goes to this code:
![image](https://github.com/VFPX/Thor/assets/116839069/ef42ab8b-2909-4b52-8b59-a78dc1280b86)

Hope this helps.

Phil

**Comment by Jimrnelson** [comment]
I have never known of a case where removing Thor is necessary.Sent from my iPadOn Oct 6, 2023, at 7:03 AM, Phil Sherwood ***@***.***> wrote:﻿
I removed Thor from my system because of problems with GoFish and reinstalled the latest using the installation instructions.
After installing and running through the update I tried to bring up the Tool Manager from the Thor menu. It gets this error.
If you suspend it goes to this code:

Hope this helps.
Phil

**Comment by Jimrnelson** [comment]
@pivoten-psherwood 

Phil --

When you re-installed Thor, did you re-install all the suggested projects (PEMEd

**Comment by pivoten-psherwood** [comment]
Jim,

I followed the installation instructions and did the 1st update and shut
down and started again before installing GoFish.

Phil

**Comment by Jimrnelson** [comment]
@pivoten-psherwood 

Phil -- thanks, that helps, my first assumption was wrong.  Am hoping to have a fix for this by Monday.

**Comment by Jimrnelson** [comment]
@pivoten-psherwood 

Hey, have not heard more from you on this Thor issue.  Is it working OK now?

**Comment by pivoten-psherwood** [comment]
Yes, it is working.

Thanks!
