### ISSUE TITLE
Thor does not update itself while run the first time. (2th)

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#227]
From #212

I think one might ask why somebody raises a problem oneself does not run into. It might happen that my POV is not the one of a customer of a Thor.

If one tries to test something on Thor (by forking or branching) it might be the simplest solution to install an old version and then update. Might fail heavy if a module or ThorRepository relies on the existence / working of a part of Thor in a new version.

Possibly there are uses to reset Thor to a blank install using modern technology that might raise the problem that a newer version is out - and one might have other things in mind then looking up Thor version every time.

Either the first run should update itself, or it should stop if there is a different version available. Autoupdate is preferred.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
Lutz --

As I have identified before, this is a problem that does not occur if one follows Thor’s installation instructions.  I am adverse to considering changes to Thor when the standard instructions are ignored.   

However, no changes to Thor are necessary to achieve what you want.  You can do so by making some simple alterations to what you call "vanilla Thor".

I suggest you create a new “vanilla Thor”, as follows:
1, Follow the standard instructions to do a normal install of Thor to a new “vanilla Thor” folder.
2. Make sure you install the three projects that Thor requires.
3. Mark as “Never Update” all projects you do not expect to normally be interested in.

That’s it.  That’s your new “vanilla Thor”, and you will never need to touch it again.  

There are some clear advantages to this:
1. You’re starting with a fully functional version of Thor.
2. When you execute `Do RunThor with 1`, it will immediately install a newer version of Thor, if one is available.
3. Since the three required projects have already been installed, you will not be forced to watch them being installed again.
4. All the projects you’re not interested in will already be marked as “Never Update”.

You could have done this at any time in the past since Thor moved to GitHub and it would serve as the proper seed for your re-installation.

**Comment by lscheffler** [comment]
@Jimrnelson I understand this very well - only the problem is about plain Thor installed from scratch, that was never run before.   

As soon as you run Thor once, it will create folders and stuff, so you can't name it *vanilla*. I use git to just reset the Thor folder to *vanilla* state.  This is a one-liner on the bash I have open anyway. Expanding the zip is a pain, by comparison.

I do this for example to test the changes to the URL in #225. It must run against a freshly copied Thor, and other states. And surely I dislike to set the *base tools*  every time. If I run tests, all 10 minutes or so.   
So for my convenience I have several states of Thor in my repo, and reset to the one I need to test.

**Comment by Jimrnelson** [comment]
Thor 1.47 - Released 2024-01-04
