### ISSUE TITLE
Cannot see Git and Hg Utilities in THOR Applications sub menu after following setup instructions

### ISSUE THREAD

**Issue by karlwillis** [VFPX/Thor#259]
Hi,
I recently installed Thor with a view to linking a VFP project to a GIT repository. However,
I seemed to have followed the instructions but I never can see a menu option for  Git and Hg Utilities in the Thor Applications submenu nor does it feature in the Options submenu as described in the documentation. I've updated Thor many times and it does pull over and setup FoxBin2 program  and Git and Hg Utilities but never sets the  Git and Hg Utilities  up and put it in the Applications menu?

Thanks

Karl

**Comment by Jimrnelson** [comment]
@karlwillis 

The image below (from your personal message to me) reveals what the problem is: Thor installed all the Git/HG utilities in the wrong folder:

![image](https://github.com/VFPX/Thor/assets/81179335/23df868b-5dac-4ba8-8941-194fa656ab10)

You can correct this by moving all the git files from that folder (`*GIT*.*`) into a sub-folder two layers down:  Thor\Tools.  (There should already be hundreds of files in that Tools folder.)

I believe that this should take care of the problem but please let us know otherwise.

**Comment by karlwillis** [comment]
Yes Jim that seems to have done the trick!
Thank you
