### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by BobWilkes** [VFPX/Thor#280]
## 📝 Provide detailed reproduction steps (if any)
Selecting Thor (ver 1.47.04) Configure throws a Type mismatch error

### ✔️ Expected result
Display of Config dialog
### ❌ Actual result
Type Mismatch Error
## 📷 Screenshots
![image](https://github.com/user-attachments/assets/483d308b-1257-4b79-94cf-35d5462112e1)

**Comment by Jimrnelson** [comment]
@BobWilkes 

Bob --

Is this still an issue?

If so, what happens if you ignore the error (possibly repeatedly)?  Can you get to the point (eventually) where the form opens?  Can you send an image of the form?

**Comment by Jimrnelson** [comment]
@BobWilkes 

A difficult one...

First of all, have you been using Thor before this?  Was there ever a time when this config screen worked correctly for you?  If so, how recently?  

Then, if you could try it again:

- please show image of the entire Call Stack (your image was truncated on the right)
- please show the locals window instead of the watch list.
- indicate what you can learn (if anything) about loNode.  Is it null, perhaps?  If not, what are the properties?

**Comment by BobWilkes** [comment]
Been using Thor for many years. Config  screen worked AOK up until about a month ago.
Yesterday when I tried it it was still out of whack.
TODAY it opened AOK. (Go figure...full moon, perhaps?
Abounding happiness!
I'll let you kn ow if ti goes astray again.
