### ISSUE TITLE
Path used when installing tools

### ISSUE THREAD

**Issue by DougHennig** [VFPX/Thor#41]
Reference _Screen.cThorFolder instead of the explicit path when Thor installs and creates tools. This makes the Thor folder completely relocatable.

**Comment by Jimrnelson** [comment]
@DougHennig 

I've been giving this problem some thought and have come up with a somewhat feasible solution.  

The reason Thor is not relocatable is that when VFPX projects (PEM Editor and GF, mainly) "register" with Thor to create tools, they embed the full path of the Thor folder into those tools.  

This can be corrected by adding just a few lines to the "Register" method in Thor to use _Screen.cThorFolder instead, which is always the folder in which Thor.App is executed.  Problem solved.

Except that this will only solve the problem (I think) for projects that are re-installed as part of CFU.  We can force this to happen for common projects, of course, but that's a piecemeal approach as I see tools in my Thor\Tools folder from many projects, and I am not suggesting tinkering with all of them

So I think we would need a second part, which would be to create a procedure to modify all the Tools in Thor\Tools  to use _Screen.cThorFolder.   This sounds dangerous, though, too, so am not sure whether it would be worth pursuing.  (Not that this would not have to even use GF, it's a simple StrTran()

I welcome comments.

**Comment by DougHennig** [comment]
I think we can leave existing installed tools alone. If I really want to make them portable, I can delete and then reinstall them.

**Comment by Jimrnelson** [comment]
Yeah, after writing that, I realized that if PEMEditor and GF came over OK, Thor would be workable to download the others; or, the others could be gotten all together or as needed.

For me, the list is very short, actually -- I see only these few tools

![image](https://user-images.githubusercontent.com/81179335/227313043-7563dba0-a3fd-4428-a5ed-ce5b812bf0f6.png)

There are many more references to the full path name, but I believe that they are not relevant.

**Comment by lscheffler** [comment]
If you tell me what I should change in GF, it's no problem to do.

**Comment by Jimrnelson** [comment]
There really is nothing to be changed in GF or any other app that registers tools with Thor.

In GF, this is handled by its updater (which is not even maintained in GF, it's maintained in Thor).  It has this line:

``.RegisterWithThor     = 'Do "##InstallFolder##GoFish5.APP" with "Thor", .T.'``

The registration process replace ##InstallationFolder## with the actual path to the installation folder.

I will be changing that process so that the code will refer to _Screen.cThorFolder and avoid the explicit path reference.

**Comment by Jimrnelson** [comment]
Today's release of Thor 1.45.12 now addresses this problem, at least partially.

From now on, tools that are "registered with Thor" (such as PEM Editor) will use _Screen.cThorDispatcher instead of an explicit path.

GF is an exception (because of how it registers with Thor.)  This happens every time you open GF, so the tools are all corrected as soon as you open GF.  (You might look at the tool for GF to see this new reference).

**Comment by Jimrnelson** [comment]
@DougHennig 

I believe that this item is done, at least as far as it can be.  To be fully relocatable, users should reinstall all projects.  

Actually, though, all they need to do is to reinstall all that reference their home folder for Thor (not many projects actually do -- only Apps, not Components.)

Hmm -- that might be a good column to add to CFU, no?  App/Component?
