### ISSUE TITLE
Update window out of visible area

### ISSUE THREAD

**Issue by lscheffler** [VFPX/Thor#75]
## 📝 Provide detailed reproduction steps (if any)

1. Set up two monitors
2. Update Thor
3. Move update FORM to second monitor and close
4. Set up only one monitor
5. Update Thor

### ✔️ Expected result
Update FORM should be visible

### ❌ Actual result
Update FORM is **not** visible

## Hint
Check GoFish gf_baseform OF gofishui.vcx, methods Init and LoadFormSettings for code moving the window into visible area. Procedure is in gofishproc.prg

**Comment by Jimrnelson** [comment]
@lscheffler 

Fixed in version 1.45.10

**Comment by lscheffler** [comment]
As the update runs, the form was between two screens - very odd. This could be just the stored value, anyway, what do you think to move such a form into one monitor?     
This is meant as a discussion, since it is the same for example GoFish

**Comment by Jimrnelson** [comment]
Before Tuesday, this issue was at or near the bottom of all the Thor and Thor-related issues (i.e, non-work) that I handle.  Apparently, a workaround had been found, else there would have been a follow-up about being unable to update Thor.

Late Tuesday afternoon, however, this escalated to the highest priority for me, as a bizarre set of circumstances combined to make it essential in solving a work issue that demanded immediate resolution.

By adding just a few simple lines to the form, I was able to both solve this Thor issue and the work problem at once.  I had no time to pursue anything more complex than that.

**Comment by lscheffler** [comment]
E.G. My original solution was to put multiple monitors to my laptop at home and move the form where it belongs. Guess how this will work on the road. So I call it a no-solution. For that the issue was posted.

And, for that my last message was a discussion. It looks to be rare - and one might simply move the form. It's just a bit of work for unoccupied moments I would do on GoFish, and Thor might participate or not. i just like to know others POV

**Comment by lscheffler** [comment]
Now the update-form opens to cheap. The form is forced into main monitor, instead to keep the position *as long as possible*.   
My main monitor is not the one I use for VFP, not even the center one. If I move the update form into VFP screen, close and reload, it always open into the main monitor - and then in the corner next possible to the old position. If I close at center of main, it's restored at bottom of main, keeping left. This is to awkward.

The repositioning should only happen if the old view area is out of the visible area.

**Comment by Jimrnelson** [comment]
This sounds like a new issue.

**Comment by lscheffler** [comment]
Moves
