### ISSUE TITLE
First installation error

### ISSUE THREAD

**Issue by DanielCarlos231** [VFPX/Thor#91]
I found an error that is happening with version "Thor - 1.45.17 - April 6, 2023- 20230406"
The variable "lnLastVersion" is returning .NULL.  when you execute:
````
Execscript(_Screen.cThorDispatcher, 'Get Option=', ccLastVersionSeen, ccTool)
````
In the Thor_Main you guys compare the veriable "lnLastVersion" with "m.lnHTMLVersion" which at that time is a number 
````
If m.llCheckFirst And m.lnHTMLVersion = m.lnLastVersion
	Return
Endif
````
so I added a NVL() to fix the error
````
lnLastVersion = Nvl(Execscript(_Screen.cThorDispatcher, 'Get Option=', ccLastVersionSeen, ccTool),0)
If m.llCheckFirst And m.lnHTMLVersion = m.lnLastVersion
	Return
Endif
````
 
![image](https://user-images.githubusercontent.com/89362488/230671513-2dfe15ec-ae45-4a23-931a-75de1fa5e6a8.png)

**Comment by Jimrnelson** [comment]
Most disappointing I had not provided for this.  Thanks for providing such a clear description of the problem.

It turns out that the effect of this is rather minor -- you should be able to just ignore for as many times as necessary to complete CFU.  (Actually, it was 99% done, just looking for News).

I will have a fix out later today.

**Comment by DanielCarlos231** [comment]
Thaks
